package src.enums;

import java.io.Serializable;

public enum SheetType implements Serializable {
	CONSTANT, ORDER_SHEET, PAYMENT_SHEET, STORAGE_IN_SHEET, STORAGE_OUT_SHEET, 
	RECEIVING_MONEY_SHEET, HALL_RECEIVING_GOODS_SHEET, CENTER_RECEIVING_GOODS_SHEET, 
	HALL_TRUCK_SHEET, CENTER_TRUCK_SHEET,CENTER_GOODS_OUT_SHEET,HALL_GOODS_OUT_SHEET;
}
